all_plausible_action_json = [
    {"action": "PICKUP", "arg1": "33120"},
    {"action": "MOVE_DIRECTION", "arg1": "west"},
    {"action": "ROTATE_DIRECTION", "arg1": "north"},
    {"action": "PUT", "arg1": "33120", "arg2": "35632"},
    {"action": "PICKUP", "arg1": "35632"},
    {"action": "ROTATE_DIRECTION", "arg1": "east"},
    {"action": "MOVE_DIRECTION", "arg1": "east"},
    {"action": "ROTATE_DIRECTION", "arg1": "south"},
    {"action": "OPEN", "arg1": "18573"},
    {"action": "MOVE_DIRECTION", "arg1": "south"},
    {"action": "USE", "arg1": "21559", "arg2": "35632"},
    {"action": "USE", "arg1": "57736", "arg2": "35632"},
    {"action": "USE", "arg1": "8549", "arg2": "35632"},
    {"action": "USE", "arg1": "55934", "arg2": "35632"},
    {"action": "USE", "arg1": "51739", "arg2": "35632"},
]

all_plausible_action_mapper = {
    "Move west": {"action": "MOVE_DIRECTION", "arg1": "west"},
    "Move east": {"action": "MOVE_DIRECTION", "arg1": "east"},
    "Move south": {"action": "MOVE_DIRECTION", "arg1": "south"},
    "Rotate north": {"action": "ROTATE_DIRECTION", "arg1": "north"},
    "Rotate east": {"action": "ROTATE_DIRECTION", "arg1": "east"},
    "Rotate south": {"action": "ROTATE_DIRECTION", "arg1": "south"},
    "Rotate west": {"action": "ROTATE_DIRECTION", "arg1": "west"},
    "Pick up the key": {"action": "PICKUP", "arg1": "33120"},
    "Put the key in the jar": {"action": "PUT", "arg1": "33120", "arg2": "35632"},
    "Pick up the jar": {"action": "PICKUP", "arg1": "35632"},
    "Use the dispenser A to deliver substance A to the jar": {"action": "USE", "arg1": "21559", "arg2": "35632"},
    "Use the dispenser B to deliver substance B to the jar": {"action": "USE", "arg1": "57736", "arg2": "35632"},
    "Use the dispenser C to deliver substance C to the jar": {"action": "USE", "arg1": "8549", "arg2": "35632"},
    "Use the dispenser D to deliver substance D to the jar": {"action": "USE", "arg1": "55934", "arg2": "35632"},
    "Wash the jar to clean substances": {"action": "USE", "arg1": "51739", "arg2": "35632"},
    "Open the door": {"action": "OPEN", "arg1": "18573"},
}

all_plausible_action_mapper_no_uuid = {
    "Move west": {"action": "MOVE_DIRECTION", "arg1": "west"},
    "Move east": {"action": "MOVE_DIRECTION", "arg1": "east"},
    "Move south": {"action": "MOVE_DIRECTION", "arg1": "south"},
    "Rotate north": {"action": "ROTATE_DIRECTION", "arg1": "north"},
    "Rotate east": {"action": "ROTATE_DIRECTION", "arg1": "east"},
    "Rotate south": {"action": "ROTATE_DIRECTION", "arg1": "south"},
    "Rotate west": {"action": "ROTATE_DIRECTION", "arg1": "west"},
    "Pick up the key": {"action": "PICKUP", "arg1": "key"},
    "Put the key in the jar": {"action": "PUT", "arg1": "key", "arg2": "jar"},
    "Pick up the jar": {"action": "PICKUP", "arg1": "jar"},
    "Use the dispenser A to deliver substance A to the jar": {"action": "USE", "arg1": "dispenser A", "arg2": "jar"},
    "Use the dispenser B to deliver substance B to the jar": {"action": "USE", "arg1": "dispenser B", "arg2": "jar"},
    "Use the dispenser C to deliver substance C to the jar": {"action": "USE", "arg1": "dispenser C", "arg2": "jar"},
    "Use the dispenser D to deliver substance D to the jar": {"action": "USE", "arg1": "dispenser D", "arg2": "jar"},
    "Wash the jar to clean substances": {"action": "USE", "arg1": "bottle_cleaner", "arg2": "jar"},
    "Open the door": {"action": "OPEN", "arg1": "door"},
}

all_action_abbr = {
    "move_west": {"action": "MOVE_DIRECTION", "arg1": "west"},
    "move_east": {"action": "MOVE_DIRECTION", "arg1": "east"},
    "move_south": {"action": "MOVE_DIRECTION", "arg1": "south"},
    "move_north": {"action": "MOVE_DIRECTION", "arg1": "north"},
    "rotate_north": {"action": "ROTATE_DIRECTION", "arg1": "north"},
    "rotate_east": {"action": "ROTATE_DIRECTION", "arg1": "east"},
    "rotate_south": {"action": "ROTATE_DIRECTION", "arg1": "south"},
    "rotate_west": {"action": "ROTATE_DIRECTION", "arg1": "west"},
    "pickup_key": {"action": "PICKUP", "arg1": "33120"},
    "put_key": {"action": "PUT", "arg1": "33120", "arg2": "35632"},
    "pickup_jar": {"action": "PICKUP", "arg1": "35632"},
    "use_dispenser_A": {"action": "USE", "arg1": "21559", "arg2": "35632"},
    "use_dispenser_B": {"action": "USE", "arg1": "57736", "arg2": "35632"},
    "use_dispenser_C": {"action": "USE", "arg1": "8549", "arg2": "35632"},
    "use_dispenser_D": {"action": "USE", "arg1": "55934", "arg2": "35632"},
    "wash": {"action": "USE", "arg1":"51739", "arg2":"35632"},
    "open_door": {"action": "OPEN", "arg1": "18573"},
}

uuid_to_name = {
    "33120": "Key",
    "35632": "Jar",
    "21559": "Dispenser A",
    "57736": "Dispenser B",
    "8549": "Dispenser C",
    "55934": "Dispenser D",
    "51739": "Bottle Cleaner",
    "18573": "Door",
}

SKILL_ALIASES = {
    "move_to_key": [
        "move to key",
        "go to key",
        "walk to key",
        "navigate to key",
    ],
    "move_to_jar": [
        "move to jar",
        "go to jar",
        "walk to jar",
        "navigate to jar",
    ],
    "move_to_dispenser_A": [
        "move to dispenser a",
        "go to dispenser a",
        "move to A dispenser",
        "move to dispenser A",
    ],
    "move_to_dispenser_B": [
        "move to dispenser b",
        "go to dispenser b",
        "move to B dispenser",
        "move to dispenser B",
    ],
    "move_to_dispenser_C": [
        "move to dispenser c",
        "go to dispenser c",
        "move to C dispenser",
        "move to dispenser C",
    ],
    "move_to_dispenser_D": [
        "move to dispenser d",
        "go to dispenser d",
        "move to D dispenser",
        "move to dispenser D",
    ],
    "pick_up_key": [
        "pick up key",
        "pickup key",
        "take key",
        "grab key",
    ],
    "put_key_in_jar": [
        "put key in jar",
        "place key in jar",
        "insert key into jar",
    ],
    "pick_up_jar": [
        "pick up jar",
        "pickup jar",
        "take jar",
        "grab jar",
    ],
    "use_dispenser_A_on_jar": [
        "use dispenser A on jar",
        "use A dispenser on jar",
        "dispense A into jar",
        "use the dispenser A to deliver substance A to the jar",
    ],
    "use_dispenser_B_on_jar": [
        "use dispenser B on jar",
        "use B dispenser on jar",
        "dispense B into jar",
        "use the dispenser B to deliver substance B to the jar",
    ],
    "use_dispenser_C_on_jar": [
        "use dispenser C on jar",
        "use C dispenser on jar",
        "dispense C into jar",
        "use the dispenser C to deliver substance C to the jar",
    ],
    "use_dispenser_D_on_jar": [
        "use dispenser D on jar",
        "use D dispenser on jar",
        "dispense D into jar",
        "use the dispenser D to deliver substance D to the jar",
    ],
    "wash_jar": [
        "wash jar",
        "clean jar",
        "rinse jar",
    ],
    "open_door": [
        "open door",
        "open the door",
    ],
}
