#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --job-name=graphgpon2
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=4:10:00
#SBATCH --output=job_log/GraphGPO-%j/output.txt
#SBATCH --error=job_log/GraphGPO-%j/error.txt


export MAX_CHEMICAL_N="${MAX_CHEMICAL_N:-2}"
export DISCOVERY_TASK="${DISCOVERY_TASK:-chemistry}"
export EXPERIMENT_NAME="${EXPERIMENT_NAME:-graphgpo-n${MAX_CHEMICAL_N}-dynamic-group4}"
export MODEL_NAME="${MODEL_NAME:-Qwen2.5-1.5B-Instruct}"
export EPOCHS="${EPOCHS:-50}"
export MAX_STEP="${MAX_STEP:-35}"
export ENV_HISTORY_LENGTH="${ENV_HISTORY_LENGTH:-4}"

export TRAIN_DATA_SIZE="${TRAIN_DATA_SIZE:-4}"
export VAL_DATA_SIZE="${VAL_DATA_SIZE:-24}"
export MINI_BATCH_SIZE="${MINI_BATCH_SIZE:-16}"
export GROUP_SIZE="${GROUP_SIZE:-4}"
export NUM_CPUS_PER_ENV_WORKER="${NUM_CPUS_PER_ENV_WORKER:-0.1}"
export ACTOR_MICRO_BATCH_SIZE_PER_GPU="${ACTOR_MICRO_BATCH_SIZE_PER_GPU:-4}"
export CRITIC_MICRO_BATCH_SIZE_PER_GPU="${CRITIC_MICRO_BATCH_SIZE_PER_GPU:-4}"
export LOG_PROB_MICRO_BATCH_SIZE_PER_GPU="${LOG_PROB_MICRO_BATCH_SIZE_PER_GPU:-4}"
export ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.40}"

export TEACHER_REWARD_COEF="${TEACHER_REWARD_COEF:-1.0}"
export LEARNING_RATE="${LEARNING_RATE:-1e-6}"
export LR_WARMUP_STYLE="${LR_WARMUP_STYLE:-constant}"
export KL_LOSS_COEF="${KL_LOSS_COEF:-0.25}"
export GRAPHGPO_MODE="${GRAPHGPO_MODE:-mean_std_norm}"
export GRAPHGPO_STEP_ADVANTAGE_W="${GRAPHGPO_STEP_ADVANTAGE_W:-1.0}"
export GRAPHGPO_GAMMA="${GRAPHGPO_GAMMA:-0.10}"
export GRAPHGPO_EPISODE_ADVANTAGE_W="${GRAPHGPO_EPISODE_ADVANTAGE_W:-1.0}"
export GRAPHGPO_NORMALIZE_DISTANCE="${GRAPHGPO_NORMALIZE_DISTANCE:-False}"
export INVALID_ACTION_PENALTY_COEF="${INVALID_ACTION_PENALTY_COEF:-2.0}"

export ENABLE_FILTER_GROUP="${ENABLE_FILTER_GROUP:-True}"
export DYNAMIC_SEED_SAMPLER="${DYNAMIC_SEED_SAMPLER:-True}"

export RESUME_MODE="${RESUME_MODE:-disable}"
export RESUME_FROM_PATH="${RESUME_FROM_PATH:-null}"

export SAVE_FREQ="${SAVE_FREQ:--1}"
export SAVE_BEST_VAL_SUCCESS="${SAVE_BEST_VAL_SUCCESS:-True}"

bash xlan/graphpo_base.sh "$@"
